In [431]:
import pandas as pd
from math import sqrt
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [432]:
df = pd.read_excel("divar_rudehen.xlsx", index_col = 0)
df.shape

(93, 15)

In [433]:
df

,نوع ملک,متراژ زمین,سال ساخت,تعداد اتاق,طبقه ملک,تعداد طبقات ساختمان,پارکینگ,آسانسور,انباری,استان,منطقه,محدوده,نوع معامله,قیمت هر متر,قیمت کل
ردیف,,,,,,,,,,,,,,,
1,ویلا,650,1402,3,0,همکف,بله,خیر,بله,تهران,رودهن,مهراباد,فروش,56923000,37000000000
2,آپارتمان,95,1402,2,8,8,بله,بله,بله,تهران,رودهن,رودهن,فروش,70000000,6650000000
3,ویلا,400,1403,2,8,همکف,بله,خیر,بله,تهران,رودهن,رودهن,فروش,32500000,13000000000
4,آپارتمان,100,1402,2,2,7,بله,بله,بله,تهران,رودهن,رودهن,فروش,60000000,6000000000
5,آپارتمان,150,1403,1,4,NAN,بله,بله,بله,تهران,رودهن,فرهنگیان,فروش,50000000,7500000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,آپارتمان,85,1396,2,1,NAN,بله,بله,بله,تهران,رودهن,رودهن,فروش,5588000,4300000000
90,آپارتمان,160,1401,3,2,NAN,بله,بله,بله,تهران,رودهن,رودهن,فروش,70000000,11200000000
91,آپارتمان,135,1396,2,6,NAN,بله,بله,بله,تهران,رودهن,رودهن,فروش,66666000,9000000000
92,آپارتمان,140,1403,2,3,NAN,بله,بله,بله,تهران,رودهن,رودهن,فروش,75000000,10500000000
93,آپارتمان,133,1404,3,5,5,بله,بله,بله,تهران,رودهن,رودهن,فروش,57894000,7700000000

In [434]:
df.drop(["تعداد طبقات ساختمان", "محدوده"], axis=1, inplace=True)

In [435]:
a = df['نوع ملک'].value_counts()
a

نوع ملک
آپارتمان    71
ویلا        22
Name: count, dtype: int64

In [436]:
print(df.columns)

Index(['نوع ملک', 'متراژ زمین', 'سال ساخت', 'تعداد اتاق', 'طبقه ملک',
       'پارکینگ', 'آسانسور', 'انباری', 'استان', 'منطقه', 'نوع معامله',
       'قیمت هر متر', 'قیمت کل'],
      dtype='object')

In [437]:
pd.set_option('future.no_silent_downcasting', True)
df.replace({
    "نوع ملک": {"آپارتمان": 0, "ویلا": 1},
    "پارکینگ": {"بله": 0, "خیر": 1},
    "آسانسور": {"بله": 0, "خیر": 1},
    "انباری": {"بله": 0, "خیر": 1},
    "استان": {"تهران": 0,},
    "منطقه": {"رودهن": 0,},
    "نوع معامله": {"فروش": 0,},
}, inplace=True)

In [438]:
print(df.columns)

Index(['نوع ملک', 'متراژ زمین', 'سال ساخت', 'تعداد اتاق', 'طبقه ملک',
       'پارکینگ', 'آسانسور', 'انباری', 'استان', 'منطقه', 'نوع معامله',
       'قیمت هر متر', 'قیمت کل'],
      dtype='object')

In [439]:
df

,نوع ملک,متراژ زمین,سال ساخت,تعداد اتاق,طبقه ملک,پارکینگ,آسانسور,انباری,استان,منطقه,نوع معامله,قیمت هر متر,قیمت کل
ردیف,,,,,,,,,,,,,
1,1,650,1402,3,0,0,1,0,0,0,0,56923000,37000000000
2,0,95,1402,2,8,0,0,0,0,0,0,70000000,6650000000
3,1,400,1403,2,8,0,1,0,0,0,0,32500000,13000000000
4,0,100,1402,2,2,0,0,0,0,0,0,60000000,6000000000
5,0,150,1403,1,4,0,0,0,0,0,0,50000000,7500000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,0,85,1396,2,1,0,0,0,0,0,0,5588000,4300000000
90,0,160,1401,3,2,0,0,0,0,0,0,70000000,11200000000
91,0,135,1396,2,6,0,0,0,0,0,0,66666000,9000000000
92,0,140,1403,2,3,0,0,0,0,0,0,75000000,10500000000
93,0,133,1404,3,5,0,0,0,0,0,0,57894000,7700000000

In [440]:
df.describe()

,متراژ زمین,سال ساخت,تعداد اتاق,طبقه ملک,قیمت هر متر,قیمت کل
count,93.000000,93.000000,93.000000,93.000000,9.300000e+01,9.300000e+01
mean,238.150538,1399.430108,2.311828,2.623656,5.953398e+07,1.148322e+10
std,328.712043,4.342404,0.570631,2.151410,2.155419e+07,1.047064e+10
min,75.000000,1381.000000,1.000000,0.000000,5.588000e+06,2.700000e+09
25%,95.000000,1397.000000,2.000000,1.000000,4.807600e+07,5.700000e+09
50%,129.000000,1401.000000,2.000000,3.000000,6.000000e+07,7.900000e+09
75%,229.000000,1403.000000,3.000000,4.000000,7.361500e+07,1.380000e+10
max,2500.000000,1404.000000,4.000000,8.000000,1.100000e+08,5.700000e+10

In [441]:
X = df.loc[:,(df.columns != 'قیمت کل') & (df.columns != 'قیمت هر متر')]
Y = df['قیمت کل']

In [442]:
print(f"تعداد ویژگی‌های X: {X.shape}")
print(f"نام ستون‌های X: {X.columns.tolist()}")

تعداد ویژگی‌های X: (93, 11)
نام ستون‌های X: ['نوع ملک', 'متراژ زمین', 'سال ساخت', 'تعداد اتاق', 'طبقه ملک', 'پارکینگ', 'آسانسور', 'انباری', 'استان', 'منطقه', 'نوع معامله']

In [443]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.40, random_state = 1)
X_train.shape

(55, 11)

In [444]:
print(f"X shape{X_test.shape}")
print(f"Y shape{Y_test.shape}")

X shape(38, 11)
Y shape(38,)

In [445]:
model = LinearRegression()

In [446]:
model.fit(X_train, Y_train)

LinearRegression()

In [447]:
df

,نوع ملک,متراژ زمین,سال ساخت,تعداد اتاق,طبقه ملک,پارکینگ,آسانسور,انباری,استان,منطقه,نوع معامله,قیمت هر متر,قیمت کل
ردیف,,,,,,,,,,,,,
1,1,650,1402,3,0,0,1,0,0,0,0,56923000,37000000000
2,0,95,1402,2,8,0,0,0,0,0,0,70000000,6650000000
3,1,400,1403,2,8,0,1,0,0,0,0,32500000,13000000000
4,0,100,1402,2,2,0,0,0,0,0,0,60000000,6000000000
5,0,150,1403,1,4,0,0,0,0,0,0,50000000,7500000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,0,85,1396,2,1,0,0,0,0,0,0,5588000,4300000000
90,0,160,1401,3,2,0,0,0,0,0,0,70000000,11200000000
91,0,135,1396,2,6,0,0,0,0,0,0,66666000,9000000000
92,0,140,1403,2,3,0,0,0,0,0,0,75000000,10500000000
93,0,133,1404,3,5,0,0,0,0,0,0,57894000,7700000000

In [452]:
features_for_prediction = [1, 5000, 1404, 3, 5, 0, 0, 0, 0, 0, 0]

In [453]:
features_df = pd.DataFrame([features_for_prediction], columns=X_train.columns)

predicted_total_price = model.predict(features_df)
print(f"قیمت کل پیش‌بینی شده: {predicted_total_price[0]:,.0f} تومان")

قیمت کل پیش‌بینی شده: 105,759,312,210 تومان